### ISSUE TITLE
FlywayTestExecutionListener doesn't play well with SqlScriptsTestExecutionListner

### ISSUE THREAD

**Issue by wujek-srujek** [flyway/flyway-test-extensions#21]
Flyway's listener doesn't implement ordering, and as a result it is called as the last listener before the test method. If someone tries to use it together with Spring's SqlScriptsTestExecutionListener, the scripts are executed, and then the database is reset by Flyway.

**Comment by FlorianGWE** [comment]
At the moment it is clear why, because FlywayTestExecutionListener exist since spring version 2.5 and SqlScriptsTestExecutionListener exist since spring 4.1.

Concept for FlywayTestExecutionListener that this listener is master of the database state and version as Flyway. 

At the moment I do not understand your test use case for combination a tool like Flyway that is for  database setup and fill a database and execution for some specific SQL template base database maniupulations scripts. 

I have seen simular concepts with using special Flyway migration scripts for test and I also see database fill scripts with dbunit files. For the Dbunit part FlywayDBUnitTestExecutionListener was created in 2010.  

Please can you give me a example test configuration from you, so may be I can develop a idea to get a working solution.

**Comment by wujek-srujek** [comment]
I am not using DbUnit (I don't really like it), and it didn't occur to me to use Flyway for the migration scripts. But here is my use case:
I'm using Flyway to clean/initialize the database for every test method. Additionally, I'm using Spring Test and its Sql annotation. It has the nice characteristics that I can just name a script as my Test class / method, and it will automatically find the script and execute it. I don't need to hardcode the test SQL script names in the test.
The issue is that the Flyway listener is not ordered (as you said, because it predates it, but I guess adding the @Ordered annotation would be backwards compatible) and because of that is run at the very end of the listener list. For this reason, Spring Sql executes the scripts against the old database, possibly from another test case (which is problem no. 1) and then the database is reset by Flyway (problem no.2).

The solution I found is to just subclass FlywayTestListener and implement Ordered and tell it that Flyway should run at the very beginning, before anything else, and use this custom one. It works fine and is simple enough.

**Comment by FlorianGWE** [comment]
Ok I got the point. 

@Ordered would be a nice feature for next version, my forcast for this will be end of september.
I will think about it or a patch from you will be welcome :-)

Your workaround solution is what I also had in mind, but @Order will be better for furture usage.

**Comment by FlorianGWE** [comment]
Current development contains a implementation with ordered. 

Module flyway-test-extensions/flyway-test-samples/flyway-test-spring-samples/flyway-test-sample-spring4 contains a simple test FlywayTestWithSqlScriptsTestExecutionListenerTest that use combination of FlywayTest and SqlScriptsTestExecutionListener.
